CREATE TABLE IF NOT EXISTS "user"
(
    id SERIAL PRIMARY KEY NOT NULL,
    email CHARACTER VARYING(20) NOT NULL,
    password CHARACTER VARYING(20) NOT NULL
);
ALTER TABLE "user" ADD CONSTRAINT user_email_unique UNIQUE ("email");